# Generated by Django 4.1 on 2022-08-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseMFASecret',
            fields=[
                ('firebase_user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('encrypted_mfa_secret', models.BinaryField()),
            ],
        ),
    ]
